on:
  release:
    types:
      - published

name: release

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    environment: crates.io
    steps:
      - uses: actions/checkout@v4

      - name: publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CARGO_REGISTRY_TOKEN }}"
        run: cargo publish
